version: '3.1'

services:
  db:
    image: mysql
    container_name: contabilidade-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
                     
  adminer:
    image: adminer
    container_name: contabilidade-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
                 
  wordcard-api:
    image: alexandregoodmann/wordcard-api
    container_name: wordcard-api
    build: ./wordcard-api/
    ports:
           - "8082"
    depends_on:
           - "db"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8    

  wordcard-web:
    image: alexandregoodmann/wordcard-web
    container_name: wordcard-web
    build: ./wordcard
    ports: 
      - "8084:8084"
    depends_on:
      - "wordcard-api"
    restart: always
          
volumes:
  my-datavolume:      
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
